### ISSUE TITLE
Can't Copy the Generated Response from History & Feedback Panel UI (Visual Studio Code + Code Builder)

### ISSUE THREAD

**Issue by abrantes23** [forcedotcom/Einstein-GPT-for-Developers#10]
Can't copy the response from UI history previous responses.

Visual Studio Code
![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/135630762/76d4d546-bc95-47d6-9bdc-86c2f791d233)

Code Builder
<img width="998" alt="image" src="https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/135630762/2b709026-8c74-4c23-b4c2-31e2d6d553b1">

**Comment by jonifazo** [comment]
Hi [abrantes23](https://github.com/abrantes23)!  Thank you for this feedback. We will investigate and get back to you soon.

**Comment by gbockus-sf** [comment]
Hi @abrantes23!
If you highlight the prompt while the row is expanded it will collapse, but if you copy at that point you'll get the entire prompt.  Thanks for the feedback.  We've discussed having some copy buttons in there.  We'll see if we can make it more user friendly.

![2023-09-14_17-19-44 (1)](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/76090802/d9b01b0e-c9fa-47f4-afee-c9dbda04589b)

**Comment by klewis-sfdc** [comment]
Internal WI created for this issue: W-14141880.

**Comment by randi274** [comment]
We've got a fix open to address the issue where the row is collapsing, so highlighting to copy + paste will soon be much easier!

On further exploration, the root cause of the copy not working is due to this VS Code bug: https://github.com/microsoft/vscode/issues/141080. The workaround for now is to highlight the text you want to work with and from there you may use the context menu or ctrl+c.
