### ISSUE TITLE
No documentation present for Connected App OAuth Scope for Einstein GPT Services

### ISSUE THREAD

**Issue by rohitasare7** [forcedotcom/Einstein-GPT-for-Developers#34]
I am exploring the connected app OAuth Scopes and I can see "Access Einstein GPT services (einstein_gpt_api)" , I would like to know if there is any documentation on this scope, how to use / access the einstein gpt api.
I checked Salesforce Documents but couldn't find anything.
Appreciate the help!

![image](https://github.com/forcedotcom/Einstein-GPT-for-Developers/assets/5638449/c18bb4b9-fb62-4718-977a-7f82e8c51f1a)

**Comment by rohitasare7** [comment]
@AnanyaJha @sbudhirajadoc do we have any documentation on this?

**Comment by gbockus-sf** [comment]
Hi @rohitasare7 
Sorry for the delay.  I don't believe that scope is related to the E4D extension or the associated service.  We use a JWT/perm that is unique to the service (and enabled for all org by default since TDXish time frame), and an alpha API (hence the beta status of the product).  There's a whole lotta einstein and related going on at salesforce so I would guess that's for some other AI service at Salesforce. I'm going to close this issue as unrelated, but feel free to reopen if we can assist.
