### ISSUE TITLE
.sfdx Folder Created for NON Salesforce Projects

### ISSUE THREAD

**Issue by vincekruger** [forcedotcom/Einstein-GPT-for-Developers#65]
### Summary

A .sfdx folder is created with +3k files on every project when VSCode is opened, even though it's not a Salesforce project.  I now have to disable and enable the salesforce extension pack all the time.
This isn't a very pleasant experience.

### Steps To Reproduce:

Open a non-Salesforce project.

### Expected result

This shouldn't happen.

### Additional information

**Salesforce Extension Version in VS Code**:
60.8.0 - April 10, 2024

**SFDX CLI Version**:
@salesforce/cli/2.29.5 darwin-arm64 node-v20.11.0

**OS and version**:
MacOS 14.4.1 (23E224)

**VS Code version**:
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z (6 days ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by peternhale** [comment]
I verified that in a non-sfdx project, having E4D installed/enabled triggers the start of other extensions.

**Comment by klewis-sfdc** [comment]
We have merged a fix for this issue that will be included in the next release of Einstein for Developers.  If this issue is affecting you, one way to workaround would be to install an older version of the E4D extension and use v0.43.1 until the next release is published.  Please let us know if this issue is still present for you after the next release is published.
